apiVersion: v1
kind: Service

metadata:
  name: pythonapp

spec:
  template:
    spec:
      containers:
        - image: ankurpatel/pythonapp:v1
          env:
            - name: APP
              value: "Python App v1"
